version: '3.9'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: mynewpassword
      POSTGRES_DB: bookdb
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - "5432"   

  redis:
    image: redis:7-alpine
    restart: always
    expose:
      - "6379"

  api:
    build: .
    env_file: .env
    depends_on:
      - db
      - redis
    ports:
      - '3000:3000'
    # optional: for hot-reload in dev
    # command: npm run start:dev

volumes:
  db-data:
